apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freshflow.fullname" . }}-runtime
  labels:
    {{- include "freshflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  FRESHFLOW_POSTGRES_PASSWORD: {{ .Values.demoSecret.postgresPassword | quote }}
  FRESHFLOW_POSTGRES_DSN: {{ printf "postgres://%s:%s@%s-postgres:5432/%s?sslmode=disable" .Values.demoSecret.postgresUser .Values.demoSecret.postgresPassword (include "freshflow.fullname" .) .Values.demoSecret.postgresDatabase | quote }}
  FRESHFLOW_CLICKHOUSE_USER: {{ .Values.demoSecret.clickhouseUser | quote }}
  FRESHFLOW_CLICKHOUSE_PASSWORD: {{ .Values.demoSecret.clickhousePassword | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freshflow.fullname" . }}-runtime
  labels:
    {{- include "freshflow.labels" . | nindent 4 }}
data:
  FRESHFLOW_ENV: local-kubernetes
  FRESHFLOW_LOG_LEVEL: info
  FRESHFLOW_HTTP_ADDR: ":8080"
  FRESHFLOW_REDIS_ADDR: {{ printf "%s-redis:6379" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_KAFKA_BROKERS: {{ printf "%s-kafka:9092" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_CLICKHOUSE_ADDR: {{ printf "%s-clickhouse:9000" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_CLICKHOUSE_DATABASE: freshflow
  FRESHFLOW_CATALOG_SERVICE_URL: {{ printf "http://%s-catalog-service:8081" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_CART_SERVICE_URL: {{ printf "http://%s-cart-service:8082" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_ORDER_SERVICE_URL: {{ printf "http://%s-order-service:8083" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_DELIVERY_SERVICE_URL: {{ printf "http://%s-delivery-service:8084" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_ANALYTICS_SERVICE_URL: {{ printf "http://%s-analytics-worker:8087" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_ETA_SERVICE_URL: {{ printf "http://%s-eta-service:8090" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_API_GATEWAY_UPSTREAM: {{ printf "%s-api-gateway:8080" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_OTEL_EXPORTER_OTLP_ENDPOINT: {{ printf "%s-jaeger:4317" (include "freshflow.fullname" .) | quote }}
  FRESHFLOW_OTEL_SAMPLE_RATIO: "1"
  FRESHFLOW_STARTUP_TIMEOUT: 30s
  FRESHFLOW_DEPENDENCY_CHECK_TIMEOUT: 2s
  FRESHFLOW_SHUTDOWN_TIMEOUT: 10s
  FRESHFLOW_CLICKHOUSE_HOST: {{ printf "%s-clickhouse" (include "freshflow.fullname" .) | quote }}
